<?php ?>

 <div><button class="socloz" data-socloz-service="reservation" data-socloz-product-id="ABC1234" data-socloz-product-id_type="internal" id="soclozbutton" style="position: relative; backface-visibility: hidden;border: 1px solid; border-radius: 5px;cursor: pointer; float: left;width : 100% ;margin: 0 10px 10px 0;overflow: visible;  padding: 7px 10px;transition: all 500ms ease 0s;background-color:#464646; border-color: #464646;color: #fff;font-size: 14px;font-style: normal;
font-weight: normal;font: 700 125%/1.55 Lato,Helvetica Neue,Helvetica,Arial,sans-serif;">RESERVER</button></div>

<?php endif; ?>